### ISSUE TITLE
alignment of images

### ISSUE THREAD

**Issue by travisdowns** [ewanmellor/git-diff-image#18]
Am I correct that the diff tends to center the two images relative to each other? E.g., I had two images that were identical except that the second one had some extra content at the bottom (making it taller overall), you'd end up centering the images during the diff meaning that everything would show in red since the second image is now shifted relative to the first?

It might be nice to be able to specify the alignment of images to handle these cases.

**Comment by ewanmellor** [comment]
We use ImageMagick's `compare` program to do the actual comparison.  I've only skimmed their doc, but I'm guessing that the `-gravity` option might be what you're looking for.

In any case, if you wanted to pass additional flags through to compare, patches are very much welcome.

**Comment by travisdowns** [comment]
Thanks for the reply and sorry I was not able to submit a patch.
