### ISSUE TITLE
Trying to create a binary patch file

### ISSUE THREAD

**Issue by sm11963** [ewanmellor/git-diff-image#2]
When trying to create a path file like `git diff master myfeature --binary > mypatch.patch` having diff.image.command set to git-diff-image makes the patch fail since it still uses the text description provided by git_diff_image. 

Is there a way to handle the --binary flag and disable the custom image diff? Or maybe an simple way (behind and alias) to enable/disable the custom image diff.

**Comment by ewanmellor** [comment]
You want:

    git diff master myfeature --binary --no-ext-diff > mypatch.patch

That looks like it's working.  Feel free to reopen if not!

**Comment by sm11963** [comment]
Awesome thanks for such a quick reply!
