### ISSUE TITLE
Add bitmap support

### ISSUE THREAD

**Issue by pkess** [ewanmellor/git-diff-image#20]
Is there an easy way to integrate support for .bmp images?

**Comment by ewanmellor** [comment]
I think everything should just work with .bmp images.  You probably just need to register it as a supported file type.  Add it to install.sh line 70 and see if that works.

I'll take the PR if it does.

**Comment by pkess** [comment]
Thank you for your comment. I had a try and bmp file support worked well. I am closing this to continue discussion in #21
