### ISSUE TITLE
Where are generated images stored?

### ISSUE THREAD

**Issue by tir38** [ewanmellor/git-diff-image#22]
This isn't working for me. I'd like to at least verify that diff images are being created.

**Comment by ewanmellor** [comment]
It uses `mktemp` to make a temporary file (diff-image line 169).

Add `set -x` to the top of diff-image (and git_diff_image if you have to).  That will log everything that it's doing, you can hopefully see where it gives up.

**Comment by tir38** [comment]
It turns out that `git diff` (not your tool) doesn't like my path/file naming convention. My filename is tripping up the regex in `.gitattributes`

**Comment by hannesa2** [comment]
I want to automate this on github actions, so I want to only generate diff files and don't view it.

I figured out [here](https://github.com/ewanmellor/git-diff-image/blob/master/diff-image#L249) is the file, 
`exec open "$destfile"`
but I want to prevent to change this file `diff-image` and probably there is already a command line to do this save of diff file, is there one ?
