### ISSUE TITLE
How make it work with git lfs files ?

### ISSUE THREAD

**Issue by amadeu01** [ewanmellor/git-diff-image#24]
I tried to run with images hosted on git lfs, but it does not show the differences.

**Comment by tir38** [comment]
Looks like this would need to be fixed in LFS itself, and they don't plan on supporting images IIUC https://github.com/git-lfs/git-lfs/issues/440

**Comment by amadeu01** [comment]
I added `diff=image` to my `.gitattributes` as a extra diff tooling and that seems to work !

```
*.png filter=lfs diff=lfs diff=image merge=lfs -text
```

**Comment by ewanmellor** [comment]
@amadeu01 Thank you!  I've added that to the README.
