### ISSUE TITLE
Only copy diff image without showing [FOLLOW UP]

### ISSUE THREAD

**Issue by hannesa2** [ewanmellor/git-diff-image#29]
```
$ GIT_DIFF_IMAGE_OUTPUT_DIR=diffs git diff-image
$ ls diffs/
example-comparison.png
```

_Originally posted by @ewanmellor in https://github.com/ewanmellor/git-diff-image/issues/27#issuecomment-1362030119_

That's tricky 😀 But it works (almost) ! 

I run into 
<img width="850" alt="image" src="https://user-images.githubusercontent.com/3314607/209067104-ba7ccd6a-621b-44bd-8d98-1a98d41c0fe9.png">
and I've to `:q` in my vim to continue. On a CI can't do this. Is there already an option to do it without this interaction ?
Or how to do this silent ?

**Comment by ewanmellor** [comment]
@hannesa2 I don't expect that to be a problem on CI.  git will know that it's not talking to a terminal, so it won't launch vim like that.  All that text will just go into the CI logs.

That said, if you wanted to add a `-s` (silent) option to skip the Exif step I'd be fine with that.

**Comment by hannesa2** [comment]
I did a [test run](https://github.com/AppDevNext/MPAndroidChart/pull/77) on CI and run into
<img width="424" alt="image" src="https://user-images.githubusercontent.com/3314607/209288383-aa9b0731-66d7-4ea6-bb64-4d85c7be219f.png">

Do you understand what's wrong here ?

**Comment by ewanmellor** [comment]
@hannesa2 I pushed a fix, try that.

**Comment by hannesa2** [comment]
@ewanmellor Thank you for your afford. Unfortunately the `install.sh` still comes with an [error](https://github.com/AppDevNext/AndroidChart/actions/runs/3779847785/jobs/6425442709)

<img width="506" alt="image" src="https://user-images.githubusercontent.com/3314607/209519266-dae644b0-0a04-4729-a3ea-d619d65ff111.png">
 
I'm based on cfdbc7a45b75e019b83b2dbf631813a33427a8fe

**Comment by hannesa2** [comment]
I made it more verbose
```
set -x

echo "current term=$TERM"
cols=80
# True if string is not empty.
if [ -n "$TERM" ]
then
  echo "Before set cols to $cols"
  cols=$(tput cols)
  echo "After set cols to $cols"
else
  echo "term=$TERM"
fi
```
<img width="490" alt="image" src="https://user-images.githubusercontent.com/3314607/209523702-11c2b0c4-b009-4556-a81c-9ba2066ff117.png">

**Comment by ewanmellor** [comment]
OK, so it has set TERM=dumb, we should skip that too. Add that to the new if statement. (TERM=dumb basically means "I'm lying I don't know what the terminal really is").

**Comment by hannesa2** [comment]
Please see my proposal https://github.com/ewanmellor/git-diff-image/pull/31 At least for me it's working properly

**Comment by ewanmellor** [comment]
Closing this, #31 is merged.
