### ISSUE TITLE
Fails when trying to open an image generated by iphone simulator under xcode

### ISSUE THREAD

**Issue by papley** [ewanmellor/git-diff-image#32]
Trying to compare the two files attached, I get this error. For that matter the browser doesn't want to open the one created in xcode either, but Preview.app has no trouble with it.

Warning: Non-standard PNG image (Apple iPhone format) - imagetest/image.new.png
compare: CgBI: unhandled critical chunk `imagetest/image.new.png' @ error/png.c/MagickPNGErrorHandler/1492.

-------

`% ./diff-image imagetest/*
--- imagetest/image.new.png
+++ imagetest/image.old.png
@@ -1,19 +1,14 @@
 Apple Data Offsets              : (Binary data 28 bytes, use -b option to extract)
 Bit Depth                       : 8
-Blue X                          : 0.15
-Blue Y                          : 0.06
 Color Space                     : sRGB
-Color Type                      : RGB with Alpha
+Color Type                      : RGB
 Compression                     : Deflate/Inflate
 Exif Byte Order                 : Big-endian (Motorola, MM)
 Exif Image Height               : 1136
 Exif Image Width                : 640
-File Size                       : 62 kB
+File Size                       : 68 kB
 File Type                       : PNG
 Filter                          : Adaptive
-Gamma                           : 2.2
-Green X                         : 0.3
-Green Y                         : 0.6
 Image Height                    : 1136
 Image Size                      : 640x1136
 Image Width                     : 640
@@ -23,12 +18,7 @@
 Pixel Units                     : meters
 Pixels Per Unit X               : 5669
 Pixels Per Unit Y               : 5669
-Red X                           : 0.64
-Red Y                           : 0.33
 Resolution Unit                 : inches
 SRGB Rendering                  : Perceptual
-Warning                         : Non-standard PNG image (Apple iPhone format)
-White Point X                   : 0.3127
-White Point Y                   : 0.329
 X Resolution                    : 144
 Y Resolution                    : 144
Warning: Non-standard PNG image (Apple iPhone format) - imagetest/image.new.png
compare: CgBI: unhandled critical chunk `imagetest/image.new.png' @ error/png.c/MagickPNGErrorHandler/1492.
phillipapley@AGPAPLEYMBP git-diff-image % ./diff-image imagetest/*
--- imagetest/image.new.png
+++ imagetest/image.old.png
@@ -1,19 +1,14 @@
 Apple Data Offsets              : (Binary data 28 bytes, use -b option to extract)
 Bit Depth                       : 8
-Blue X                          : 0.15
-Blue Y                          : 0.06
 Color Space                     : sRGB
-Color Type                      : RGB with Alpha
+Color Type                      : RGB
 Compression                     : Deflate/Inflate
 Exif Byte Order                 : Big-endian (Motorola, MM)
 Exif Image Height               : 1136
 Exif Image Width                : 640
-File Size                       : 62 kB
+File Size                       : 68 kB
 File Type                       : PNG
 Filter                          : Adaptive
-Gamma                           : 2.2
-Green X                         : 0.3
-Green Y                         : 0.6
 Image Height                    : 1136
 Image Size                      : 640x1136
 Image Width                     : 640
@@ -23,12 +18,7 @@
 Pixel Units                     : meters
 Pixels Per Unit X               : 5669
 Pixels Per Unit Y               : 5669
-Red X                           : 0.64
-Red Y                           : 0.33
 Resolution Unit                 : inches
 SRGB Rendering                  : Perceptual
-Warning                         : Non-standard PNG image (Apple iPhone format)
-White Point X                   : 0.3127
-White Point Y                   : 0.329
 X Resolution                    : 144
 Y Resolution                    : 144
Warning: Non-standard PNG image (Apple iPhone format) - imagetest/image.new.png
compare: CgBI: unhandled critical chunk `imagetest/image.new.png' @ error/png.c/MagickPNGErrorHandler/1492.
<img width="320" alt="image new" src="https://user-images.githubusercontent.com/1513087/228022588-71782af5-4128-4809-bafc-56910a9c9912.png">
<img width="320" alt="image old" src="https://user-images.githubusercontent.com/1513087/228022592-faaec709-cfda-461e-8d2a-82bf440a4a93.png">`

**Comment by ewanmellor** [comment]
This is nothing to do with git-diff-image, sorry.  We use `compare` from ImageMagick for all the heavy lifting, so you should raise this issue with them.

Googling `compare: CgBI: unhandled critical chunk` gives a number of old discussion threads, you could also check if any of those are still current.

**Comment by papley** [comment]
No problem. Thanks for the quick reply.
