### ISSUE TITLE
GraphicMagick as alternative dependency?

### ISSUE THREAD

**Issue by ottok** [ewanmellor/git-diff-image#37]
Does git-diff-image use any features that are [ImageMagick](https://imagemagick.org/) specific, or does it work with [GraphicMagic](http://www.graphicsmagick.org/) as well?

If anybody has already tested it and has knowledge, please note results in this issue.

If not, let's keep the issue open until GraphicsMagic compatibility is documented.

**Comment by ewanmellor** [comment]
@ottok No-one has tried to my knowledge (I had not even heard of GraphicsMagick until you mentioned it).

**Comment by ottok** [comment]
I tested it now myself and since the shell script of the tool is quite easy to read, I cooked up PR#38 to add this. Please don't merge this immediately but wait for 1-2 weeks for feedback from others. I prefer to perfect it instead of making follow-up PRs.
