### ISSUE TITLE
Public domain dedication not the same as CC0

### ISSUE THREAD

**Issue by amueller** [ewanmellor/git-diff-image#8]
Hey.
Thanks for a cool project.
I noticed that you put a public domain dedication on the bottom of the readme and then link to CC0. These two things are not the same. "public domain" is a concept in US law, and for example in Germany, it's not possible to dedicate anything to the public domain. CC0 takes this into account and creates a legal framework that works in many countries, not only the US. So I'd recommend saying more explicitly it's licensed under CC0, not that it's public domain, even though the two are equivalent in the US.

Cheers,
Andy

**Comment by ewanmellor** [comment]
Thanks for the comment, but I'm not going to be retrospectively changing the license on this code.

**Comment by amueller** [comment]
That's fair, though outside of the US this doesn't have a valid license right now and so probably defaults to "all rights reserved". Not saying it's an actual issue, totally get it if you don't want to bother with it.
